name: Build

#on: [pull_request]
on: [push]

jobs:
  build:
    name: JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: [1.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      - name: Extract version
        run: |
          echo ::set-env name=VERSION_NAME::$(cat gradle.properties | grep -w "VERSION_NAME" | cut -d'=' -f2)
          echo $env.VERSION_NAME

      - name: Remove "-SNAPSHOT" from Version
        run: |
          sed -i'' "s/VERSION_NAME=.*-SNAPSHOT/VERSION_NAME=${env.VERSION_NAME}/g" gradle.properties
          cat gradle.properties



#      - name: Build with Gradle
#        run: ./gradlew build --stacktrace